/**
 * Default pool of "still working" messages for patient timeout mode.
 * Consumers can pass this as `patienceMessage` in TuiAppConfig, or provide
 * their own string, array, or function.
 */
export const DEFAULT_PATIENCE_MESSAGES: readonly string[] = [
  "I promise I'm not ignoring you...",
  "I'll be with you shortly...",
  "Still crunching the numbers...",
  "Good things come to those who wait...",
  "Working hard behind the scenes...",
  "Just a little longer...",
  "Rome wasn't built in a day...",
  "Patience is a virtue, they say...",
  "Thinking really hard about this one...",
  "Almost there... probably...",
  "My hamsters are running as fast as they can...",
  "The bits are flowing, I assure you...",
  "Making progress, pinky promise...",
  "This is the part where you grab a coffee...",
  "I'm not stuck, I'm being thorough...",
  "Running a few more errands for you...",
  "Just dotting some i's and crossing some t's...",
  "Your patience is appreciated...",
  "Gathering all the puzzle pieces...",
  "The wheels are turning, trust me...",
  "Hold tight, the magic is happening...",
  "Brewing up something good...",
  "Still on it — haven't forgotten about you...",
  "Processing at the speed of thought... my thought...",
  "If you're reading this, I'm still working...",
  "This one's taking a bit of elbow grease...",
  "Consulting my sources...",
  "Assembling the final report...",
  "Bear with me, this is a big one...",
  "Working through a mountain of data...",
  "The research rabbit hole goes deep...",
  "Connecting the dots...",
  "Just negotiating with the internet...",
  "Herding cats is easier than this...",
  "Loading... loading... still loading...",
  "I've seen slower, but not by much...",
  "Trust the process...",
  "Meanwhile, in a parallel universe, this is already done...",
  "Warming up the flux capacitor...",
  "Rearranging electrons for your convenience...",
];
